### ISSUE TITLE
AssertionError: number too large

### ISSUE THREAD

**Issue by fadaytak** [dannycoates/franz-kafka#11]
assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: number too large
    at toDouble (/Users/******_/node_modules/franz-kafka/node_modules/int53/index.js:53:3)
    at Object.int53.readInt64BE (/Users/**_**/node_modules/franz-kafka/node_modules/int53/index.js:62:9)
    at Function.ZnodeStat.parse (/Users/*****_/node_modules/franz-kafka/node_modules/zkjs/protocol/znode-stat.js:20:29)
    at GetDataResponse.parse (/Users/**_***_/node_modules/franz-kafka/node_modules/zkjs/protocol/get-data.js:32:30)
    at Receiver.read (/Users/**_****_/node_modules/franz-kafka/node_modules/zkjs/receiver.js:91:16)
    at Receiver.streamReadable (/Users/**_****/node_modules/franz-kafka/node_modules/zkjs/receiver.js:112:8)
    at Client.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)

solution ???

**Comment by pastarace** [comment]
Same issue using:

``` javascript
var kafka = new Kafka({zookeeper: ['localhost:2181']});
```
